// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M5StickCplus2TEST03

#ifndef _M5STICKCPLUS2TEST03_UI_H
#define _M5STICKCPLUS2TEST03_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_baby_90_png);   // assets/baby_90.png

// FONTS
LV_FONT_DECLARE( ui_font_D2CodingBold22);
LV_FONT_DECLARE( ui_font_D2CodingBoldV1L22);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Font22);
LV_FONT_DECLARE( ui_font_NanumGothic16);
LV_FONT_DECLARE( ui_font_NanumGothic22);
LV_FONT_DECLARE( ui_font_NanumGothicBold22);
LV_FONT_DECLARE( ui_font_korea22);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
