// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M5StickCplus2TEST04

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Spinner2 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_MainText1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Arc1 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner2 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner2, 30);
lv_obj_set_height( ui_Spinner2, 30);
lv_obj_set_x( ui_Spinner2, 50 );
lv_obj_set_y( ui_Spinner2, 100 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xB0B0B0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner2, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -8 );
lv_obj_set_y( ui_Label6, -96 );
lv_obj_set_align( ui_Label6, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label6,"G");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_baby_90_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 140
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 90
lv_obj_set_y( ui_Image1, 17 );
lv_obj_set_x( ui_Image1, lv_pct(1) );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,255);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 158);
lv_obj_set_height( ui_Panel2, 64);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -53 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xC4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -7 );
lv_obj_set_y( ui_Label1, -98 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"project");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainText1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_MainText1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainText1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainText1, 0 );
lv_obj_set_y( ui_MainText1, -52 );
lv_obj_set_align( ui_MainText1, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainText1,"Vocabulary");
lv_obj_set_style_text_color(ui_MainText1, lv_color_hex(0xD8D8D8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainText1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MainText1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainText1, &ui_font_Font22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -2 );
lv_obj_set_y( ui_Label2, 74 );
lv_obj_set_align( ui_Label2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label2,"0/0");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 35);
lv_obj_set_height( ui_Arc1, 38);
lv_obj_set_x( ui_Arc1, 0 );
lv_obj_set_y( ui_Arc1, 90 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc1, 0,999);
lv_arc_set_value(ui_Arc1, 999);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xB0B0B0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xB0B0B0), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 3 );
lv_obj_set_y( ui_Label3, 76 );
lv_obj_set_align( ui_Label3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label3,"0V");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_obj_set_width( ui_Bar1, 90);
lv_obj_set_height( ui_Bar1, 5);
lv_obj_set_x( ui_Bar1, -19 );
lv_obj_set_y( ui_Bar1, 111 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xB0B0B0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 3 );
lv_obj_set_y( ui_Label4, 94 );
lv_obj_set_align( ui_Label4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label4,"0%");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -46 );
lv_obj_set_y( ui_Label5, -102 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Ck");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0x002EFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 38 );
lv_obj_set_y( ui_Label7, -96 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"<<");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 54 );
lv_obj_set_y( ui_Label8, -113 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"B");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Spinner2= NULL;
ui_Label6= NULL;
ui_Image1= NULL;
ui_Panel2= NULL;
ui_Label1= NULL;
ui_MainText1= NULL;
ui_Label2= NULL;
ui_Arc1= NULL;
ui_Label3= NULL;
ui_Bar1= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
ui_Label7= NULL;
ui_Label8= NULL;

}
